---
# ServiceAccount for Jenkins Agent
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: jenkins-agents-hungpq52

---
# Role in jenkins-agents namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-agent
  namespace: jenkins-agents-hungpq52
rules:
  # Agent needs to manage pods for dynamic provisioning
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["*"]
  # Agent may need to read ConfigMaps and Secrets
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

---
# RoleBinding in jenkins-agents namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent
  namespace: jenkins-agents-hungpq52
subjects:
  - kind: ServiceAccount
    name: jenkins-agent
    namespace: jenkins-agents-hungpq52
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-agent

---
# Role in petclinic namespace for build and deploy
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer
  namespace: petclinic-hungpq52
rules:
  # Build permissions
  - apiGroups: ["build.openshift.io"]
    resources: ["builds", "buildconfigs"]
    verbs: ["*"]
  # Image permissions
  - apiGroups: ["image.openshift.io"]
    resources: ["imagestreams", "imagestreamtags"]
    verbs: ["get", "list", "create", "update"]
  # Deployment permissions
  - apiGroups: ["apps", "apps.openshift.io"]
    resources: ["deployments", "deploymentconfigs"]
    verbs: ["*"]
  # Service and Pod permissions
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["*"]
  # Route permissions
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["*"]

---
# RoleBinding in petclinic namespace (cross-namespace)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer
  namespace: petclinic-hungpq52
subjects:
  - kind: ServiceAccount
    name: jenkins-agent
    namespace: jenkins-agents-hungpq52
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-deployer
