apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-controller
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-controller-agent-provisioner
  namespace: jenkins
rules:
  # Tạo / xoá / theo dõi Pod agent
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get","list","watch","create","delete"]
  # Kubernetes plugin thường tạo Secret cho JNLP hoặc mount credential
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","watch","create","delete"]
  # Nếu bạn dùng PodTemplate bằng ConfigMap hoặc cần đọc cấu hình
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-controller-agent-provisioner
  namespace: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins-controller
    namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-controller-agent-provisioner
